language: csharp
solution: GettyImages.Api.sln
mono: none
dotnet: 2.1.4
script:
- dotnet restore
- dotnet build -c Release
- dotnet test UnitTests/
notifications:
  slack:
    rooms:
      secure: SmSNslDyIqfgCwV46mwmD+XlgQnwDym3I0uZIuH8tMM9YFWJO6Kx2htG/9f5nP/pBoFkM7kV5jPxWno0xCopZtXf0gRs/q8StvFqM7N1DVgHdjpZ8BSEPgGtV1nrpU3yNKJzWHVCNBjwAFVjgr95U7NbeP7ZHrGfcK6Kt85k1JrFlZuiI9J5mXZcJ62ePV2PmupIEfBRJdCvidGZ66PIoy/R+FKf2Z9q6f7rBNZESacFLdS8BqvVbV0BUKcu04OotU6EDjQu6r7d7vT9Oj8fMJRlzNwGM+5DxdOBimqDT7rFkcBreR4UrkJRrINN/8qbt+qDRnnzXTv92qkM/cRJI8fjVEGP/nvul7DKX3dboJGjkqwgKJAYRD70AQgslGm59JrRhNYKlbL+0vdCKpewFBTxu1+smcJMtUOBm1MQ82KgcYzO3twouUngmWdKlr8rpEWvlXmdmfqWrGPT866iEY8UKCqP/RbdLgz7USqaq3XEsxGxGnqe1ZpHIKUx7xecEHYYz2GLaBVaSW+pEBZsMjyEHOdwL96IyF58IMAFwGgZtm75lxfPXtz+aK09W/uljrFuielqSmEM3x0xkWA5siuX69fcvBbV0bwmYtqR/qobjSM3IqXNTx5wPTJxl/Z0isMiHBbWd1pcE3rleQa4Do7pUwiXRYC48dagwyLMUxk=
    on_success: always
